version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskly-app
    restart: always
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=https://taskly.mhg-int.com
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql://taskly_user:supersecurepass@dockerized-laravel-db-aftdx6:5432/taskly
      - DB_PORT=5432
      - DB_DATABASE=taskly
      - DB_USERNAME=taskly_user
      - DB_PASSWORD=supersecurepass
    ports:
      - "8000:80"
    networks:
      - taskly-net

  db:
    image: postgres:16
    container_name: taskly-db
    restart: always
    environment:
      - POSTGRES_DB=taskly
      - POSTGRES_USER=taskly_user
      - POSTGRES_PASSWORD=supersecurepass
    volumes:
      - taskly-data:/var/lib/postgresql/data
    networks:
      - taskly-net

networks:
  taskly-net:

volumes:
  taskly-data:
